package com.icloud.framework.core.common;

public enum ReturnCode {
	SUCCESS("S00200"),

	ERROR("E00500"),

	E_DUPKEY("E00501"),

	E_DUPNAME("E00502"),

	E_NOTEXISTS("E00503"),
	// 数据校验失败
	E_DATA_VALIDATION_ERROR("E00504"),
	// 返回了多条记录
	E_MORE_THAN_ONE_RECORD_FOUND("E00505"),
	// 页号越界
	E_PAGEINDEX_OUT_OF_BOUNDS("E00506"),

	E_LOGIN("E00400"),

	E_INVALID_AMOUNT("E00601"),

	E_STATUS_ERROR("E00600"),

	S_REDIRECT("S00000"),

	E_TIMEOUT("E00600"),

	E_NOFARE("E00700"),
	// 银行前置adapter实例化失败
	E_BANKPRE_GATEADAPTER_INSTANTIATION_ERROR("E01501"),
	// 银行前置adapter当前还不支持此功能
	E_BANKPRE_ADAPTER_NOT_SUPPORT_FUNCTION("E01502"),
	// 银行前置，签名失败
	E_BANKPRE_SIGN_FAIL("E01503"),
	// 银行前置，验签失败
	E_BANKPRE_DESIGN_FAIL("E01504"),
	// 支付网关-支付金额不等于订单金额
	E_PAYGATE_PAYAMOUNT_NOT_EQUAL_ORDERAMOUNT("E02501"),
	// 支付网关-支付订单号重复
	E_PAYGATE_PAYORDERNO_DUPLICATE("E02502"),
	// 支付网关-不存在此gateId
	E_PAYGATE_NO_SUCH_GATEID("E02503"),
	// 支付网关-支付结果与支付请求的关键字段不匹配
	E_PAYGATE_KEY_FIELDS_NOT_MATCHED_BETWEEN_PAYRESULT_AND_PAYREQ("E02504"),
	// 支付网关-订单重复支付
	E_PAYGATE_ORDER_DUPLICATE_PAY("E02505"),
	// 支付网关-找不到原支付记录
	E_PAYGATE_NO_SUCH_PAYDETAIL("E02506"),
	// 支付网关-原支付成功的订单又被通知支付失败
	E_PAYGATE_ORDER_STATE_CONFLICT("E02507"),
	// 酒店预订错误信息
	E_HOTEL_RESERVATION_ERROR("E03400"),
	// 订单-当前状态下不能调账
	E_ORDER_ILLEGAL_STATE_CANNOT_INIT_ADJUSETMENT("E04600"),
	// 订单-当前状态下不能支付
	E_ORDER_ILLEGAL_STATE_CANNOT_FROZEN("E04500"),
	// 订单-当前状态下不能完成出票
	E_ORDER_ILLEGAL_STATE_CANNOT_COMPLETE("E04501"),
	// 订单-当前状态下不能更新冻结状态
	E_ORDER_ILLEGAL_STATE_CANNOT_UPDATE_FROZEN_STATE("E04502"),
	// 订单-当前状态下不能更新解冻状态
	E_ORDER_ILLEGAL_STATE_CANNOT_UPDATE_UNFROZEN_STATE("E04503"),
	// 订单-当前状态下不能取消受理出票
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PROCESS_ISSUE("E04504"),
	// 订单-当前状态下不能受理出票
	E_ORDER_ILLEGAL_STATE_CANNOT_PROCESS_ISSUE("E04505"),
	// 订单-当前状态下不能审核订单
	E_ORDER_ILLEGAL_STATE_CANNOT_REVIEW_ORDER("E04507"),
	// 订单-当前状态下不能取消订单
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_ORDER("E04508"),
	// 退废订单-当前状态下不能取消受理退废审核
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PROCESS_REFUND_REVIEW("E04509"),
	// 退废订单-当前状态下不能审核通过退废审核
	E_ORDER_ILLEGAL_STATE_CANNOT_PASS_REFUND_REVIEW("E04510"),
	// 退废订单-当前状态下不能审核不通过退废审核
	E_ORDER_ILLEGAL_STATE_CANNOT_FAIL_REFUND_REVIEW("E04511"),
	// 退废订单-当前状态下不能保存退废订单
	E_ORDER_ILLEGAL_STATE_CANNOT_SAVE_REFUND_ORDER("E04512"),
	// 退废订单-当前状态下不能修改退废审核
	E_ORDER_ILLEGAL_STATE_CANNOT_MODIFY_REFUND_REVIEW("E04513"),
	// 退废订单-当前状态下不能提交审核退废订单
	E_ORDER_ILLEGAL_STATE_CANNOT_REQUEST_REFUND_REVIEW("E04514"),
	// 退废订单-退废pnr状态，客票座位取消等信息有误
	E_ORDER_ILLEGAL_STATE_PNR_STATE_REFUND("E04515"),
	// 订单-没有可用舱位
	E_ORDER_NO_CABIN("E04551"),
	// 订单-运价变动
	E_ORDER_FARE_CHANGE("E04552"),
	// 订单-乘客变动
	E_ORDER_PASSENGER_CHANGE("E04553"),
	// 订单-行程变动
	E_ORDER_ITINERARY_CHANGE("E04554"),
	// 订单-pnr解析失败
	E_ORDER_PNR_PARSE_ERROR("E04555"),
	// 订单-未找到对应的成人订单
	E_ORDER_NO_ADULT_ORDER("E04556"),
	// 订单-航段不可退
	E_ORDER_SEGMENT_NOT_REFUNDABLE("E04557"),
	// 订单-每个退废订单只能有一个pnr
	E_ORDER_REFUND_ORDER_CAN_ONLY_HAS_ONE_PNR("E04558"),
	// 订单-不识别此orderType
	E_ORDER_CANNOT_RECOGNIZE_ORDER_TYPE("E04559"),
	//订单-某些乘客的票不能覆盖pnr的整个行程
	E_ORDER_PASSENGER_MISSING_SOME_TICKET("E04560"),
	//订单-当前状态下不能取消处理退票
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PROCESS_REFUND("E04561"),
	//订单-当前状态下不能取消审核通过
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_REFUND_REVIEW_PASS("E04562"),
	//订单-当前状态下不能完成退票
	E_ORDER_ILLEGAL_STATE_CANNOT_COMPLETE_REFUND("E04563"),
	//订单-当前状态下不能受理退票完成
	E_ORDER_ILLEGAL_STATE_CANNOT_PROCESS_REFUND("E04564"),
	//订单-当前状态下不能受理退票确认
	E_ORDER_ILLEGAL_STATE_CANNOT_PROCESS_REFUND_CONFIRM("E04565"),
	//订单-未出票
	E_ORDER_TICKET_NOT_ISSUED("E04566"),
	//订单-当前状态下不能更改收银状态
	E_ORDER_ILLEGAL_STATE_CANNOT_UPDATE_GATHERING_STATE("E04567"),
	//订单-当前状态下不能取消收银
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_GATHERING("E04568"),
	//订单-提交的退票信息跟从pnr中解析出的不匹配
	E_ORDER_SUBMITTED_REFUND_REQ_NOT_MATCH_PARSED_FROM_PNR("E04569"),
	//退废订单-当前状态下不能完成收银
	E_ORDER_ILLEGAL_STATE_CANNOT_COMPLETE_GATHERING("E04570"),
	//退废订单-pnr非退废pnr
	E_ORDER_PNR_NOT_REFUNDED("E04571"),
	//改签订单-当前状态下不能保存改签订单
	E_ORDER_ILLEGAL_STATE_CANNOT_SAVE_ENDORSE_ORDER("E04572"),

	//改签订单-存在不可改签的航段
	E_ORDER_SEGMENT_NOT_ENDORSABLE("E04573"),

	//改签订单--当前状态下不能提交改签订单
	E_ORDER_ILLEGAL_STATE_CANNOT_APPLY_ENDORSE_REVIEW("E04574"),
	//改签订单--当前状态下不能审核
	E_ORDER_ILLEGAL_STATE_CANNOT_REVIEW_ENDORSE_ORDER("E04575"),
	//改签订单--当前状态下不能处理
	E_ORDER_ILLEGAL_STATE_CANNOT_PROCESS_ENDORSE_ORDER("E04576"),
	//改签订单--当前状态下不能进行取消受理
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PROCESS_REVIEW("E04577"),
	//改签订单--当前状态下不能进行退回改签审核
	E_ORDER_ILLEGAL_STATE_CANNOT_FAIL_REVIEW("E04578"),
	//改签订单--当前状态下不能进行审核
	E_ORDER_ILLEGAL_STATE_CANNOT_PASS_REVIEW("E04579"),
	//改签订单--当前状态下不能进行提交改签处理
	E_ORDER_ILLEGAL_STATE_CANNOT_APPLY_PROCESS("E04580"),

	E_SESSION_EXPIRED("E00701"),

	//改签订单--当前状态下不能取消受理处理
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PROCESS_ENDORSE_ORDER("E04581"),
	// 订单-当前状态下不能退回订单

	E_ORDER_ILLEGAL_STATE_CANNOT_RETURN_ORDER("E04582"),

	//改签订单--当前状态下不能请求收银
	E_ORDER_ILLEGAL_STATE_CANNOT_REQ_GATHERING("E04583"),

	//改签订单--当前状态下不能取消改签审核通过
	E_ORDER_ILLEGAL_STATE_CANNOT_CANCEL_PASS_REVIEW("E04584"),
	//正常订单-当前状态下不能拒绝出票
	E_ORDER_ILLEGAL_STATE_CANNOT_REJECT_ISSUE("E04585"),
	//正常订单-当前状态下不能挂起订单
	E_ORDER_ILLEGAL_STATE_CANNOT_SUSPEND_ORDER("E04586"),
	//正常订单-当前状态下不能恢复挂起订单
	E_ORDER_ILLEGAL_STATE_CANNOT_RESUME_ORDER("E04587"),
	//正常订单-该pnr没有出过票
	E_ORDER_PNR_NOT_ISSUED("E04588"),
	//无权限
	E_ORDER_AUTHORIZATION_ERROR("E04589"),
	//正常订单-没有操作员处理
	E_ORDER_HAS_NO_OPERATOR("E04590"),
	//只有受理人才能解挂
	E_ORDER_ONLY_OWNER_RESUME_ORDER("E04591"),
	//当前状态下不能受理审核
	E_ORDER_ILLEGAL_STATE_CANNOT_PROCESS_REVIEW("E04592"),
	//pnr已出票，1个月内不允许重复创建
	E_ORDER_CANNOT_IMPORT_ISSUED_PNR("E04593"),
	//pnr已生成订单，订单仍在处理中
	E_ORDER_PNR_PROCESSING("E04594"),
	//当前状态下不能价格申请
	E_ORDER_ILLEGAL_STATE_CANNOT_PRICE_APPLY("E04595"),
	//当前状态下不能保存审核
	E_ORDER_ILLEGAL_STATE_CANNOT_SAVE_REVIEW("E04596"),
	//正常订单当前状态下不能退回审核
	E_ORDER_ILLEGAL_STATE_CANNOT_FAIL_NORMAL_REVIEW("E04597"),
	//正常订单当前状态下不能审核通过
	E_ORDER_ILLEGAL_STATE_CANNOT_REVIEW_PASS("E04598"),
	//只有当前受理人才能操作
	E_ORDER_ONLY_CURRENT_OPERATOR("E04599"),
	//暂不能出票
	E_ORDER_ILLEGAL_STATE_CANNOT_TMP_REJECT("E04600"),
	//没有主管权限
	E_ORDER_HAS_NO_DIRECTOR_PERMISSION("E04601"),
	//出票office号需要授权
	E_ORDER_TICKET_OFFICE_NO_NEED_AUTHORIZED("E04602"),
	// 订单-客票不可退
	E_ORDER_TICKET_NOT_REFUNDABLE("E04603"),
	// 订单-客票不可改签
	E_ORDER_TICKET_NOT_ENDORSABLE("E04604"),
	// 订单-只能改签原客票
	E_ORDER_ONLY_ENDORSE_ORIG_ETICKET("E04605"),
	//订单-pnr已导入过
	E_ORDER_PNR_ALREADY_IMPORTED("E04606"),
	//订单-实退金额不能大于实收金额
	E_ORDER_REFUND_AMT_CANNOT_EXCEED_PAY_AMT("E04607"),
	//订单-不能重复提交改签
	E_ORDER_DUPLICATE_ENDORSE("E04608"),
	//订单-不能强制派单
	E_ORDER_ILLEGAL_STATE_CANNOT_ASSIGN_ORDER("E04609"),
	//订单-操作员不在队列中
	E_ORDER_OPERATOR_NOT_IN_QUEUE("E04610"),
	// can't create order, cause account is freezen.
	E_ACCOUNT_IS_FREEZEN("E04611"),
	

	/**---------------------酒店返回码-----------------*/
	
	
	//酒店订单错误code范围 1～1000
	HOTEL_ORDER_CREATE_ORDER_PARAM_ERROR("HOTEL_ORDER_0001"),		//创建订单参数错误
	
	HOTEL_ORDER_ORDER_HOTEL_INVALIDED("HOTEL_ORDER_0002"),	//用户预订的酒店不能预订
	HOTEL_ORDER_ROOM_NOT_ENOUGH_ERROR("HOTEL_ORDER_0003"),//房间库存不足
	
	HOTEL_ORDRE_STATE_OPERATION_ERROR("HOTEL_ORDER_0004"),	//订单状态和操作不匹配
	HOTEL_ORDER_GATHERING_STATE_ERROR("HOTEL_ORDER_0005"),	//收款记录更新失败
	HOTEL_ORDER_FLOW_ERROR("HOTEL_ORDER_0006"),	//受理错误
	
	HOTEL_ORDER_ORI_ORDER_ERROR("HOTEL_ORDER_0007"),	//原定单错误
	
	HOTEL_ORDER_DATA_LOGIC_ERROR("HOTEL_ORDER_0008"),	//酒店订单金额数据不一致错误
	HOTEL_ORDER_POSTGRESS_ERROR("HOTEL_ORDER_0009"),	//pg数据库错误

	HOTEL_ORDER_FINANCE_ERROR("HOTEL_ORDER_0010"),	//财务失败
	HOTEL_ORDER_MEMBER_ERROR("HOTEL_ORDER_0011"),	//获取用户信息失败


	//酒店维护错误code
	HOTEL_DATABASE_MODEL_ERROR("HOTEL_1001"),	//酒店数据模型错误
	
	//公共错误
	HOTEL_MONGO_ERROR("HOTEL_MONGO_1"),		//mongodb错误
	HOTEL_POSTGRESS_ERROR("HOTEL_PG_2"),	//postgress数据库错误
	HOTEL_REFRESH_REDIS_ERROR("HOTEL_REDIS_ERROR"),//redis错误



	/**-------------------------机票返回码--------------------*/
	FLIGHT_PNR_USER_NOT_EXIST("FLIGHT_PNR_0001"),  //用户信息不存在，请选择输入
	FLIGHT_PNR_NOT_EXIST("FLIGHT_PNR_0002"), // PNR不存在
	FLIGHT_PNR_LENGTH_ERROR("FLIGHT_PNR_0003"),//PNR长度有误
	FLIGHT_PNR_HAS_OUT("FLIGHT_PNR_0004"),//"改PNR已出票"
	FLIGHT_NOT_KNOW_ERROR("FLIGHT_PNR_0005"),//"未知错误"
	FLIGHT_PNR_SERVER_ERROR("FLIGHT_PNR_0006"),//服务器返回错误
	FLIGHT_PNR_SUCCESS("FLIGHT_PNR_0007"),//成功无错误
	FLIGHT_PNR_ADT_TICKETNO_ERROR("FLIGHT_PNR_0008"),   //成人票号错误
	FLIGHT_PNR_RR_TICKET_ERROR("FLIGHT_PNR_0009"), //RR需要给出提示框
	//FLIGHT_PNR_INTERNATIONAL_TICKET_OUT("FLIGHT_PNR_0010"),//国际已经导入过给出提示框
	FLIGHT_PNR_OTHER_ERROR("FLIGHT_PNR_0000"),//其他错误

	/**------------------------HTTP 回码--------------------*/

	HTTP_HOSTCONNECT_EXCEPTION("E10001"),
	HTTP_SOCKET_EXCEPTION("E100002"),
	HTTP_SOCKET_TIMEOUT("E100003"),
	HTTP_NO_RESPONSE_EXCEPTION("E10004"),
	HTTP_CONNECT_TIMEOUT("E10005"),
	HTTP_PARSE_EXCEPTION("E10006"),
	HTTP_IO_EXCEPTION("E100007"),


	/**---------------------报表相关------------------------------*/
	REPORT_HOTEL_PG_ERROR("REPORT_PG_ERROR_0001"),

	/**-------------------------旅游相关--------------------*/
	JOURNEY_PARAMTER_NO_EXIST_TOUR_GROUP_ID("JOURNEY_PARAMTER_NO_EXIST_TOUR_GROUP_ID"), // 旅游团ID参数不存在
	
	JN_SEARCH_ERROR("JN_SEARCH_ERROR_0001"),//搜索错误


	/**------------------------保险订单---------------------*/
	INSURANCE_UNDERWRITE_ERROR("INSURANCE_ERROR_0001"),//投保错误
	INSURANCE_ABORT_ERROR("INSURANCE_ERROR_0002"),//撤保错误
	INSURANCE_SEARCH_ERROR("INSURANCE_ERROR_003"),//搜索错误
	INSURANCE_ARG_ERROR("INSURNACE_ERROR_004"),//参数错误
	INSURANCE_SAVE_ERROR("INSURANCE_ERROR_05"),//保存订单错误
	INSURANCE_INSURER_MIN_AGE_ERROR("INSURNACE_ERROR_006"),//保险人最小年龄限制
	INSURANCE_INSUREE_MIN_AGE_ERROR("INSURANCE_ERROR_007"),//被保人最小年龄限制
	INSURANCE_INSUREE_MAX_AGE_ERROR("INSURANCE_ERROR_008"),//被保人最大年龄限制
	INSURANCE_SUBMIT_ERROR("INSURANCE_ERROR_009"),//提交失败
	INSURANCE_CANCEL_ERROR("INSURANCE_ERROR_010"),//取消失败
	INSURANCE_PAY_ERROR("INSURANCE_ERROR_011"),//支付错误
	INSURANCE_UNDERWRITE_SHOW_MESSAGE("INSURANCE_MESSAGE_0001"),//保险投保提示
	
	/**------------------------签证---------------------*/
	VISA_SEARCH_ERROR("VISA_ERROR_001"),//搜索错误
	
	/**------------------------财务相关---------------------*/
	FINANCE_UNKNOWN_ERROR("FINANCE_ERROR_0001"),
	FINANCE_UNVERIFIED("FINANCE_ERROR_0002"),
	FINANCE_ACCOUNT_FREEZE_ERROR("FINANCE_ERROR_0003"),
	FINANCE_ACCOUNT_NOT_EXIST_ERROR("FINANCE_ERROR_0004"),
	FINANCE_ACCOUNT_AMOUNT_CACULATE_ERROR("FINANCE_ERROR_0005"),
	FINANCE_UPDATE_DB_ERROR("FINANCE_ERROR_0006"),
	FINANCE_ALREADY_CHECKOUT_ERROR("FINANCE_ERROR_0007"),
	FINANCE_RECHARGE_TOO_MANY_ACCOUNTS_ERROR("FINANCE_ERROR_0008"),
	FINANCE_NOT_ENOUGH_AMOUNT_ERROR("FINANCE_ERROR_0009"),
	FINANCE_DEDUCT_TOO_MUCH_AMOUNT_ERROR("FINANCE_ERROR_0010"),
	FINANCE_CREDIT_EXPIRED_ERROR("FINANCE_ERROR_0011"),
	FINANCE_NETPAY_REFUND_REQUEST_ERROR("FINANCE_ERROR_0012"),
	FINANCE_NOTIFY_REFUND_ERROR("FINANCE_ERROR_0013"),
	FINANCE_WRONG_PARAMS_ERROR("FINANCE_ERROR_0014"),
	FINANCE_WRONG_PARAMS_STATUS_ERROR("FINANCE_ERROR_0015"),
	FINANCE_WRONG_PARAMS_AMOUNT_ERROR("FINANCE_ERROR_0016"),
	FINANCE_CHECKOUT_NO_DEBT_ERROR("FINANCE_ERROR_0017"),
	FINANCE_CHECKOUT_HAS_DEBT_ERROR("FINANCE_ERROR_0018"),
	FINANCE_CHECKOUT_RECHARGE_NOT_ENOUGH_ERROR("FINANCE_ERROR_0019"),
	FINANCE_ORIG_NO_CHECKOUT_ERROR("FINANCE_ERROR_0020"),
	FINANCE_DUPLICATED_CREDIT_NAME_ERROR("FINANCE_ERROR_0021"),
	FINANCE_ACCOUNT_ORDER_CREDIT_AMOUNT_CACULATE_ERROR("FINANCE_ERROR_0022"),
	FINANCE_ACCOUNT_CONTRACT_CREDIT_AMOUNT_CACULATE_ERROR("FINANCE_ERROR_0023"),
	FINANCE_ACCOUNT_TEMP_CREDIT_AMOUNT_CACULATE_ERROR("FINANCE_ERROR_0024"),
	FINANCE_ACCOUNT_FREEZE_AMOUNT_CACULATE_ERROR("FINANCE_ERROR_0025"),
	FINANCE_TEMP_CREDIT_END_DATE_ERROR("FINANCE_ERROR_0026"),
	FINANCE_CREDIT_PERIOD_IS_NULL_ERROR("FINANCE_ERROR_0027"),
	FINANCE_ACCOUNT_TYPE_IS_ERROR("FINANCE_ERROR_0028"),
	FINANCE_CREDIT_DUPLICATED_ERROR("FINANCE_ERROR_0029"),
	FINANCE_INVALID_PAY_TYPE("FINANCE_ERROR_0030"),
	FINANCE_UNCOMPLETED_PARAMS_VALUE("FINANCE_ERROR_0031"),
	FINANCE_DEBT_NEED_TO_PAY("FINANCE_ERROR_0032"),
	FINANCE_ORDER_CREDIT_CANCEL("FINANCE_ERROR_0033"),
	FINANCE_THIRDPAY_NOTIFY_ERROR("FINANCE_ERROR_0034"),
	FINANCE_ACCOUNT_AUTH_FAIL("FINANCE_ERROR_0035"),
	FINANCE_ORDER_ALREADY_PAID("FINANCE_ERROR_0036"),
	FINANCE_NOT_ENOUGH_PRESTORE("FINANCE_ERROR_0037"),
	;

	private String errorCode;

	ReturnCode(String code) {
		errorCode = code;
	}

	public String getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}


}
