package com.icloud.stock.model;

// Generated 2014-5-6 20:29:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer id;
	private String stockName;
	private String stockCode;
	private Date createTime;
	private Date updateTime;
	private String stockLocation;
	private String stockTypeXueqiu;
	private String descrition;
	private String stockTypeZhengjian;
	private String stockTypeBase;
	private String stockAllCode;
	private Set categoryStocks = new HashSet(0);

	public Stock() {
	}

	public Stock(String stockCode) {
		this.stockCode = stockCode;
	}

	public Stock(String stockName, String stockCode, Date createTime,
			Date updateTime, String stockLocation, String stockTypeXueqiu,
			String descrition, String stockTypeZhengjian, String stockTypeBase,
			String stockAllCode, Set categoryStocks) {
		this.stockName = stockName;
		this.stockCode = stockCode;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.stockLocation = stockLocation;
		this.stockTypeXueqiu = stockTypeXueqiu;
		this.descrition = descrition;
		this.stockTypeZhengjian = stockTypeZhengjian;
		this.stockTypeBase = stockTypeBase;
		this.stockAllCode = stockAllCode;
		this.categoryStocks = categoryStocks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStockLocation() {
		return this.stockLocation;
	}

	public void setStockLocation(String stockLocation) {
		this.stockLocation = stockLocation;
	}

	public String getStockTypeXueqiu() {
		return this.stockTypeXueqiu;
	}

	public void setStockTypeXueqiu(String stockTypeXueqiu) {
		this.stockTypeXueqiu = stockTypeXueqiu;
	}

	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

	public String getStockTypeZhengjian() {
		return this.stockTypeZhengjian;
	}

	public void setStockTypeZhengjian(String stockTypeZhengjian) {
		this.stockTypeZhengjian = stockTypeZhengjian;
	}

	public String getStockTypeBase() {
		return this.stockTypeBase;
	}

	public void setStockTypeBase(String stockTypeBase) {
		this.stockTypeBase = stockTypeBase;
	}

	public String getStockAllCode() {
		return this.stockAllCode;
	}

	public void setStockAllCode(String stockAllCode) {
		this.stockAllCode = stockAllCode;
	}

	public Set getCategoryStocks() {
		return this.categoryStocks;
	}

	public void setCategoryStocks(Set categoryStocks) {
		this.categoryStocks = categoryStocks;
	}

}
