package com.icloud.stock.model;

// Generated 2014-4-17 23:54:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer id;
	private String stockName;
	private String stockCode;
	private Date createTime;
	private Date updateTime;
	private String stockLocation;
	private String stockType;
	private String descrition;

	public Stock() {
	}

	public Stock(String stockCode) {
		this.stockCode = stockCode;
	}

	public Stock(String stockName, String stockCode, Date createTime,
			Date updateTime, String stockLocation, String stockType,
			String descrition) {
		this.stockName = stockName;
		this.stockCode = stockCode;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.stockLocation = stockLocation;
		this.stockType = stockType;
		this.descrition = descrition;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStockLocation() {
		return this.stockLocation;
	}

	public void setStockLocation(String stockLocation) {
		this.stockLocation = stockLocation;
	}

	public String getStockType() {
		return this.stockType;
	}

	public void setStockType(String stockType) {
		this.stockType = stockType;
	}

	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

}
