package com.icloud.stock.model;

// Generated 2014-4-13 23:33:37 by Hibernate Tools 3.4.0.CR1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer id;
	private String stockName;
	private String stockCode;

	public Stock() {
	}

	public Stock(String stockCode) {
		this.stockCode = stockCode;
	}

	public Stock(String stockName, String stockCode) {
		this.stockName = stockName;
		this.stockCode = stockCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

}
