package com.cloud.stock.model;

// Generated Apr 11, 2014 1:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int id;
	private String stockName;
	private String stockId;

	public Stock() {
	}

	public Stock(int id) {
		this.id = id;
	}

	public Stock(int id, String stockName, String stockId) {
		this.id = id;
		this.stockName = stockName;
		this.stockId = stockId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

}
